apiVersion: v1
name: komodor-agent
description: Watches and sends kubernetes resource-related events
icon: https://raw.githubusercontent.com/komodorio/helm-charts/master/k8s-watcher.svg
version: 2.0.4
appVersion: 0.2.62
