allowReadingPodLogs: true
collectHistory: true
controller:
  resync:
    period: "0"
enableAgentTaskExecution: false
nameDenylist:
  - leader
  - election
namespacesDenylist:
  - kube-system
redact: []
resources:
  clusterRole: true
  configMap: true
  daemonSet: true
  deployment: true
  event: true
  ingress: true
  job: true
  cronjob: true
  namespace: true
  node: true
  persistentVolume: true
  persistentVolumeClaim: true
  pod: true
  replicaSet: true
  replicationController: true
  secret: false
  service: true
  serviceAccount: true
  statefulSet: true
  storageClass: true
  endpoints: true
servers:
  healthCheck: {}
watchNamespace: all
