{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "komodorAgent.serviceAccountName" . }}
  labels:
    {{- include "komodorAgent.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if not (empty .Values.imagePullSecret) }}
imagePullSecrets:
  - name: {{ .Values.imagePullSecret }}
{{- end }}