apiVersion: v1
name: k8s-watcher
description: Watches and send kubernetes resource-related events
icon: https://raw.githubusercontent.com/komodorio/helm-charts/master/placeholder-logo.png
version: 0.17.6
appVersion: 0.1.111
