apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "otterize.mapper.configMapName" . }}
  {{- if hasKey .Values "namespace" }}
  namespace: {{ .Values.namespace }}
  {{- end }}
data: {}
binaryData: {} # mapper will add data here on runtime
