apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-watcher
  namespace: komodor
  labels:
    helm.sh/chart: k8s-watcher-1.14.1
    app.kubernetes.io/name: k8s-watcher
    app.kubernetes.io/instance: k8s-watcher
    app.kubernetes.io/version: "0.2.17"
    app.kubernetes.io/managed-by: Helm
---
