{{- if .Values.capabilities.telemetry.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "komodorAgent.fullname" . }}
  labels:
    {{- include "komodorAgent.labels" . | nindent 4 }}
    {{- with .Values.components.komodorAgent.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
  - name: http-healthz
    port: {{ .Values.components.komodorAgent.watcher.ports.healthCheck }}
    targetPort: {{ .Values.components.komodorAgent.watcher.ports.healthCheck }}
    protocol: TCP
  selector:
    {{- include "komodorAgent.watcher.selectorLabels" . | nindent 4 }}
{{- end }}
